# This is a config for E2B sandbox template.
# You can use template ID (tsh9e4xi815xf6s43sg4) or template name (codeaura-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("codeaura-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("codeaura-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codeaura-nextjs-test-2')

team_id = "2bc93b01-b155-476e-a589-bb275db57975"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codeaura-nextjs-test-2"
template_id = "tsh9e4xi815xf6s43sg4"
